[package]
name = "allnations"
version = "0.0.1"
authors = ["douglasmg7 <douglasmg7@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.13"
xml-rs = "0.8.3"
rusqlite = { version = "0.23.1", features = ["chrono"] }
