[package]
name = "allnations"
version = "0.1.3"
authors = ["douglasmg7 <douglasmg7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.4.0"
# serde = { version = "1.0.114", features = ["derive"] }
# serde-xml-rs = "0.4.0"
xml-rs = "0.8.3"
# serde = "1.0.114"
